[tool.poetry]
name = "celery-yandex-serverless"
version = "0.1.0.7"
description = ""
authors = ["atnartur <i@atnartur.ru>"]
readme = "README.md"
packages = [{include = "celery_yandex_serverless"}]

[tool.poetry.dependencies]
python = "^3.8"
django = "^4"
celery = "^5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
